### ISSUE TITLE
Host a compiled version of the game online?

### ISSUE THREAD

**Issue by Naereen** [mindylou/legend-of-zolda#1]
Hello there,

This game seems great, but as the README documentation states, « This is an easily accessible Web-based game », however it is not given with a direct URL to play the game.
I think it should be the case, so users can try it without having to install OCaml, Opam, all the dependencies, and compile it themselves.

You don't need to own a website to host it online, it could be hosted on https://mindylou.github.io/legend-of-zolda/ if you configures [GitHub pages](https://pages.github.com/) correctly.

Thanks in advance,
Regards; -- @Naereen

**Comment by Naereen** [comment]
I'm writing a course on OCaml and I want to start by showcasing a few "fun" examples of games written in OCaml, like https://mahsu.github.io/mariocaml/

**Comment by mindylou** [comment]
Hi @Naereen, you actually should be able to play at the link above (https://mindylou.github.io/legend-of-zolda/) as I have configured it with GitHub pages, there's just one asset missing that should show that you use the WASD keys to move the character around the screen. Thanks for your interest!

**Comment by Naereen** [comment]
Oh great, but you could add a link to the description of the project and the README.md.
Thanks for the quick reply!

**Comment by mindylou** [comment]
@Naereen already done, see commit 1c0e7a4. Thanks!

**Comment by Naereen** [comment]
@mindylou great!
